config/routes.rb
Rails.application.routes.draw do
  root to: 'clients#index'
  resources :clients, only: [:create]
  post '/csv_exports' => 'csv_exports#create', as: 'csv_exports'

end

app/models/client.rb
class Client < ActiveRecord::Base
  extend Model::ToCSV
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end
end

app/controllers/csv_exports_controller.rb
class CsvExportsController < ApplicationController
  before_filter :sanitize_resource_class

  def create
    csv_data = @klass.to_csv
    send_data csv_data
  end

  protected

  def sanitize_resource_class
    @klass = params[:resource_class].classify.constantize
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clients/index.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1 class="text-center">Listado de clientes</h1>
  </div>
</div>

<div class="row">
  <div class="small-8 small-centered columns">
    <table>
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Correo</th>
          <th>Teléfono</th>
          <th>Género</th>
        </tr>
      </thead>

      <tbody>
        <% @clients.each do |client| %>
          <tr>
            <th><%= client.name %></th>
            <th><%= client.email %></th>
            <th><%= client.phone_number %></th>
            <th><%= client.gender %></th>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="small-3 columns">
    <%= link_to "Descargar como CSV", csv_exports_path(resource_class: 'Client'), method: 'post' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Clientes</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>